#40 Gridlines feature
irinafakotakis/simpleCamera390 pull request #57
Opened 2019-02-19 20:33 UTC by irinafakotakis

Gridlines feature.
User can enable gridlines from settings.
Minimum SDK raised from 21 to 23 (to enable setting the foreground, adding gridlines).
Kotlin version also updated.

2019-02-20 02:16 UTC, irinafakotakis commented
Went back to amend commits to add issue # reference.

2019-02-28 16:34 UTC, Keeran10 requested changes
the variable initialization: 
`val gridlinesView : RelativeLayout = findViewById(R.id.gridlines)` [MainActivity.kt line 93] 
must account for null returns. This problem was caught during UI testing. Please refactor that line to 
`val gridlinesView? : RelativeLayout = findViewById(R.id.gridlines)`

2019-03-02 20:24 UTC, Keeran10 approved these changes

2019-03-02 20:25 UTC, Keeran10 commented
The code is well-written. Gridlines are working properly, Well done.

2019-03-02 20:26 UTC, merged